add_newline = false

format = """
$character\
$directory\
$nodejs\
$python\
$ruby\
$cmd_duration\
"""

right_format = """
$git_branch\
$git_status\
"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = false
format = "[$path]($style) "

[cmd_duration]
min_time = 2000
format = "took [$duration](yellow) "

[git_branch]
symbol = ""
format = "[$branch](bold purple) "

[git_status]
format = "[$all_status](yellow)"
conflicted = "!"
staged = "+"
modified = "·"
untracked = "·"
deleted = "·"
stashed = ""
renamed = ""
ahead = "↑"
behind = "↓"
diverged = "↕"

[nodejs]
symbol = ""
format = "[node $version](green) "

[python]
symbol = ""
format = "[py $version](yellow) "

[ruby]
symbol = ""
format = "[rb $version](red) "
