return {}

-- Treesitter for better syntax highlighting
-- {
--     'nvim-treesitter/nvim-treesitter',
--     build = ':TSUpdate',
--     config = function()
--         require('nvim-treesitter.configs').setup({
--             ensure_installed = {
--                 "lua",
--                 "vim",
--                 "javascript",
--                 "typescript",
--                 "python",
--             },
--             highlight = {
--                 enable = true,
--             },
--             indent = {
--                 enable = true,
--             },
--         })
--     end
-- },

-- -- LSP Support
-- {
--     'VonHeikemen/lsp-zero.nvim',
--     branch = 'v3.x',
--     dependencies = {
--         -- LSP Support
--         { 'neovim/nvim-lspconfig' },
--         { 'williamboman/mason.nvim' },
--         { 'williamboman/mason-lspconfig.nvim' },
--         -- Autocompletion
--         { 'hrsh7th/nvim-cmp' },
--         { 'hrsh7th/cmp-nvim-lsp' },
--         { 'L3MON4D3/LuaSnip' },
--     },
--     config = function()
--         local lsp_zero = require('lsp-zero')
--         lsp_zero.on_attach(function(client, bufnr)
--             -- Key mappings available on LSP attach
--             lsp_zero.default_keymaps({ buffer = bufnr })
--         end)
--         require('mason').setup({})
--         require('mason-lspconfig').setup({
--             ensure_installed = {
--                 'lua_ls',
--                 'tsserver',
--                 'pyright',
--             },
--             handlers = {
--                 lsp_zero.default_setup,
--             },
--         })
--     end
-- }

