# vim:set ft=tmux:
%hidden MODULE_NAME="git_branch"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󰊢 "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_green}"
set -ogq "@catppuccin_${MODULE_NAME}_text" " #(git -C #{pane_current_path} symbolic-ref --short HEAD 2>/dev/null)"

source -F "#{d:current_file}/plugins/tmux/utils/status_module.conf"
